import { Property } from "@/app/types/property-type";

const properties: Property[] = [
  {
    id: "prop-001",
    purpose: "rent",
    city: "الرياض",
    district: "الملز",
    address: "شارع الأحساء",
    location: {
      type: "Point",
      coordinates: [46.7201, 24.6663],
    },
    title: "شقة مفروشة للإيجار",
    description: "شقة حديثة قريبة من الخدمات",
    area: 120,
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-01-20",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-002",
    purpose: "sale",
    city: "الرياض",
    district: "الياسمين",
    address: "طريق أنس بن مالك",
    location: {
      type: "Point",
      coordinates: [46.6435, 24.8332],
    },
    title: "فيلا للبيع",
    description: "فيلا فاخرة بتصميم عصري",
    area: 420,
    price: 2500000,
    duration: 730,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2025-02-05",
    isRadical: true,
  },
  {
    id: "prop-003",
    purpose: "rent",
    city: "الرياض",
    district: "العليا",
    address: "شارع العليا العام",
    location: {
      type: "Point",
      coordinates: [46.6753, 24.6902],
    },
    title: "مكتب للإيجار",
    description: "مكتب مناسب للشركات الناشئة",
    area: 85,
    price: 1800,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "office",
    listedAt: "2025-02-18",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-004",
    purpose: "rent",
    city: "الرياض",
    district: "النرجس",
    address: "شارع عثمان بن عفان",
    location: {
      type: "Point",
      coordinates: [46.6679, 24.8576],
    },
    title: "شقة فاخرة للإيجار",
    description: "تشطيب راقي وموقع مميز",
    area: 160,
    price: 5200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-01",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-005",
    purpose: "sale",
    city: "الرياض",
    district: "الشفا",
    address: "شارع ديراب",
    location: {
      type: "Point",
      coordinates: [46.6402, 24.5743],
    },
    title: "دور أرضي للبيع",
    description: "مناسب للعائلات وموقع هادئ",
    area: 300,
    price: 1350000,
    bedrooms: 4,
    duration: 72,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-01-28",
    isRadical: false,
  },
  {
    id: "prop-006",
    purpose: "rent",
    city: "الرياض",
    district: "اليرموك",
    address: "شارع النجاح",
    location: {
      type: "Point",
      coordinates: [46.7845, 24.7641],
    },
    title: "شقة عائلية للإيجار",
    description: "قريبة من المدارس والخدمات",
    area: 140,
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-02-12",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-007",
    purpose: "sale",
    city: "الرياض",
    district: "الملقا",
    address: "طريق الملك فهد",
    location: {
      type: "Point",
      coordinates: [46.6408, 24.8125],
    },
    title: "شقة تمليك حديثة",
    description: "بجوار المراكز التجارية",
    area: 180,
    price: 980000,
    bedrooms: 3,
    bathrooms: 3,
    duration: 24,
    propertyType: "apartment",
    listedAt: "2025-02-22",
    isRadical: true,
  },
  {
    id: "prop-008",
    purpose: "rent",
    city: "الرياض",
    district: "قرطبة",
    address: "شارع سعيد بن زيد",
    location: {
      type: "Point",
      coordinates: [46.7412, 24.8117],
    },
    title: "مكتب إداري للإيجار",
    description: "موقع استراتيجي للشركات",
    area: 110,
    price: 3500,
    bedrooms: 0,
    bathrooms: 2,
    propertyType: "office",
    listedAt: "2025-03-05",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-009",
    purpose: "sale",
    city: "الرياض",
    district: "النسيم",
    address: "شارع الأربعين",
    location: {
      type: "Point",
      coordinates: [46.7934, 24.7041],
    },
    title: "فيلا دوبلكس للبيع",
    description: "تشطيب ممتاز وسعر مناسب",
    area: 360,
    price: 1650000,
    bedrooms: 4,
    bathrooms: 5,
    duration: 72,
    propertyType: "villa",
    listedAt: "2025-01-15",
    isRadical: false,
  },
  {
    id: "prop-010",
    purpose: "rent",
    city: "الرياض",
    district: "حطين",
    address: "شارع الأمير محمد بن سعد",
    location: {
      type: "Point",
      coordinates: [46.6239, 24.8221],
    },
    title: "شقة فاخرة مطلة",
    description: "إطلالة مميزة وتصميم عصري",
    area: 200,
    price: 7500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-10",
    duration: 730,
    isRadical: true,
  },
  // RIYADH
  {
    id: "prop-011",
    purpose: "rent",
    city: "الرياض",
    district: "النرجس",
    address: "طريق الملك سلمان",
    location: { type: "Point", coordinates: [46.642, 24.845] },
    title: "مودرن فيلا صغيرة",
    description: "فيلا مودرن بتصميم ذكي ومساحات استغلالية رائعة",
    area: 250,
    price: 12000,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-03-12",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-012",
    purpose: "rent",
    city: "الرياض",
    district: "الملقا",
    address: "شارع أنس بن مالك",
    location: { type: "Point", coordinates: [46.615, 24.808] },
    title: "استديو مؤثث بالكامل",
    description: "استديو فاخر للعزاب في أرقى أحياء الشمال",
    area: 55,
    price: 4500,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-03-14",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-013",
    purpose: "rent",
    city: "الرياض",
    district: "الياسمين",
    address: "شارع القلعة",
    location: { type: "Point", coordinates: [46.645, 24.815] },
    title: "شقة واسعة للعائلات",
    description: "قريبة من جميع الخدمات والمدارس العالمية",
    area: 160,
    price: 6000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-15",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-014",
    purpose: "rent",
    city: "الرياض",
    district: "حي السفارات",
    address: "ساحة الكندي",
    location: { type: "Point", coordinates: [46.628, 24.678] },
    title: "دوبلكس في حي السفارات",
    description: "خصوصية تامة وأمان عالي في منطقة هادئة",
    area: 320,
    price: 25000,
    bedrooms: 4,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-03-16",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-015",
    purpose: "rent",
    city: "الرياض",
    district: "العقيق",
    address: "طريق الملك فهد",
    location: { type: "Point", coordinates: [46.634, 24.782] },
    title: "شقة مطلة على المركز المالي",
    description: "إطلالة بانورامية على KAFD وتصميم عصري",
    area: 140,
    price: 8500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-18",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-016",
    purpose: "rent",
    city: "الرياض",
    district: "الصحافة",
    address: "شارع العليا",
    location: { type: "Point", coordinates: [46.631, 24.801] },
    title: "بنتهاوس مع سطح خاص",
    description: "مساحة خارجية كبيرة للتنزه واللقاءات العائلية",
    area: 210,
    price: 9000,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-20",
    duration: 730,
    isRadical: true,
  },

  // JEDDAH
  {
    id: "prop-017",
    purpose: "rent",
    city: "جدة",
    district: "الشاطئ",
    address: "طريق الكورنيش",
    location: { type: "Point", coordinates: [39.112, 21.604] },
    title: "شقة فاخرة واجهة بحرية",
    description: "استيقظ على صوت الأمواج وإطلالة البحر الأحمر",
    area: 280,
    price: 15000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-21",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-018",
    purpose: "rent",
    city: "جدة",
    district: "الروضة",
    address: "شارع حمد الجاسر",
    location: { type: "Point", coordinates: [39.148, 21.562] },
    title: "شقة في قلب الروضة",
    description: "شقة هادئة في أرقى شوارع جدة الحيوية",
    area: 180,
    price: 7000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-22",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-019",
    purpose: "rent",
    city: "جدة",
    district: "أبحر الشمالية",
    address: "شارع العابر",
    location: { type: "Point", coordinates: [39.105, 21.745] },
    title: "فيلا مودرن بمسبح خاص",
    description: "تصميم عصري واسع مع حديقة ومسبح",
    area: 400,
    price: 18000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2025-03-23",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-020",
    purpose: "rent",
    city: "جدة",
    district: "السلامة",
    address: "شارع صاري",
    location: { type: "Point", coordinates: [39.155, 21.585] },
    title: "شقة اقتصادية مريحة",
    description: "قريبة من المجمعات التجارية والمطاعم",
    area: 120,
    price: 4000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-24",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-021",
    purpose: "rent",
    city: "جدة",
    district: "الحمراء",
    address: "طريق الأندلس",
    location: { type: "Point", coordinates: [39.172, 21.515] },
    title: "شقة كلاسيكية واسعة",
    description: "أسقف عالية ومساحات واسعة بالقرب من نافورة جدة",
    area: 220,
    price: 8500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-25",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-022",
    purpose: "rent",
    city: "جدة",
    district: "المحمدية",
    address: "شارع الأمير سلطان",
    location: { type: "Point", coordinates: [39.128, 21.642] },
    title: "دوبلكس عصري فاخر",
    description: "نظام ذكي وتكييف مركزي وتشطيبات ملكية",
    area: 260,
    price: 13000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-26",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-023",
    purpose: "rent",
    city: "جدة",
    district: "البساتين",
    address: "طريق الملك",
    location: { type: "Point", coordinates: [39.115, 21.685] },
    title: "جناح فندقي خاص",
    description: "استديو فاخر بخدمات تنظيف وصيانة دورية",
    area: 70,
    price: 6500,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-03-27",
    duration: 730,
    isRadical: true,
  },

  // DAMMAM
  {
    id: "prop-024",
    purpose: "rent",
    city: "الدمام",
    district: "الشاطئ الشرقي",
    address: "طريق الخليج",
    location: { type: "Point", coordinates: [50.125, 26.452] },
    title: "شقة مطلة على الخليج",
    description: "إطلالة مباشرة على كورنيش الدمام",
    area: 190,
    price: 6500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-28",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-025",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفيصلية",
    address: "شارع عمر بن الخطاب",
    location: { type: "Point", coordinates: [50.082, 26.395] },
    title: "فيلا عائلية كبيرة",
    description: "فيلا مستقلة مع كراج خاص لسيارتين",
    area: 450,
    price: 11000,
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-03-29",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-026",
    purpose: "rent",
    city: "الدمام",
    district: "حي المنار",
    address: "شارع الإمام علي بن أبي طالب",
    location: { type: "Point", coordinates: [50.055, 26.375] },
    title: "شقة أرضية بحوش",
    description: "مدخل خاص وحوش جانبي مناسب للأطفال",
    area: 170,
    price: 3500,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-30",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-027",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفاخرية",
    address: "شارع المتنبي",
    location: { type: "Point", coordinates: [50.035, 26.345] },
    title: "شقة مودرن جديدة",
    description: "عمارة جديدة كلياً بتصميم حديث وموقف خاص",
    area: 155,
    price: 4200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-31",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-028",
    purpose: "rent",
    city: "الدمام",
    district: "حي النزهة",
    address: "شارع عثمان بن عفان",
    location: { type: "Point", coordinates: [50.11, 26.415] },
    title: "شقة مؤثثة بالكامل",
    description: "أثاث ايكيا جديد ومطبخ متكامل الأجهزة",
    area: 130,
    price: 5500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-01",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-029",
    purpose: "rent",
    city: "الدمام",
    district: "حي هجر",
    address: "طريق الرياض",
    location: { type: "Point", coordinates: [50.165, 26.285] },
    title: "فيلا للإيجار السنوي",
    description: "موقع استراتيجي بالقرب من جامعة الإمام عبدالرحمن",
    area: 300,
    price: 9500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-02",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-030",
    purpose: "rent",
    city: "الدمام",
    district: "حي الجوهرة",
    address: "شارع الخليج",
    location: { type: "Point", coordinates: [50.145, 26.442] },
    title: "شقة مطلة على الحديقة",
    description: "شقة هادئة جداً بإطلالة خضراء واسعة",
    area: 185,
    price: 5000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-03",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-031",
    purpose: "rent",
    city: "الرياض",
    district: "المصيف",
    address: "شارع زهير بن أبي سلمى",
    location: { type: "Point", coordinates: [46.6821, 24.7612] },
    title: "شقة مرممة بالكامل",
    description: "شقة في الدور الأول تم تجديدها بالكامل بمواد صحية فاخرة",
    area: 145,
    price: 4800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-05",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-032",
    purpose: "rent",
    city: "الرياض",
    district: "السليمانية",
    address: "شارع الثلاثين",
    location: { type: "Point", coordinates: [46.7011, 24.698] },
    title: "تاون هاوس في كمباوند هادئ",
    description: "بيئة سكنية آمنة مع مسبح مشترك وصالة ألعاب رياضية",
    area: 280,
    price: 16500,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-06",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-033",
    purpose: "rent",
    city: "الرياض",
    district: "قرطبة",
    address: "طريق الثمامة",
    location: { type: "Point", coordinates: [46.732, 24.814] },
    title: "ملحق راقي بسطح خاص",
    description: "خصوصية تامة مع اطلالة ليلية جميلة على شمال الرياض",
    area: 110,
    price: 5200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-07",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-034",
    purpose: "rent",
    city: "الرياض",
    district: "الرائد",
    address: "طريق الملك عبدالله",
    location: { type: "Point", coordinates: [46.641, 24.721] },
    title: "شقة فاخرة بجوار الجامعة",
    description: "قريبة جداً من جامعة الملك سعود ومستشفى الملك خالد",
    area: 190,
    price: 9500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-08",
    duration: 730,
    isRadical: true,
  },

  // JEDDAH
  {
    id: "prop-035",
    purpose: "rent",
    city: "جدة",
    district: "النعيم",
    address: "شارع حراء",
    location: { type: "Point", coordinates: [39.1412, 21.618] },
    title: "شقة واسعة جداً للعوائل",
    description: "مساحات مفتوحة وتوزيع ذكي للغرف في حي راقي ومكتمل الخدمات",
    area: 210,
    price: 6500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-04-09",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-036",
    purpose: "rent",
    city: "جدة",
    district: "المرجان",
    address: "طريق الملك عبدالعزيز",
    location: { type: "Point", coordinates: [39.101, 21.705] },
    title: "قصر مصغر بإطلالة بحرية",
    description: "تشطيبات ملكية، رخام إيطالي، ومصعد داخلي خاص",
    area: 600,
    price: 45000,
    bedrooms: 6,
    bathrooms: 7,
    propertyType: "villa",
    listedAt: "2025-04-10",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-037",
    purpose: "rent",
    city: "جدة",
    district: "النهضة",
    address: "شارع حراء",
    location: { type: "Point", coordinates: [39.125, 21.625] },
    title: "شقة دوبلكس مودرن",
    description: "تصميم طابقين مع سلم داخلي خشبي وتكييف مركزي",
    area: 240,
    price: 11000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-04-11",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-038",
    purpose: "rent",
    city: "جدة",
    district: "الصفا",
    address: "شارع السبعين",
    location: { type: "Point", coordinates: [39.201, 21.571] },
    title: "شقة اقتصادية نظيفة",
    description: "مثالية للعائلات الصغيرة قريبة من الأسواق المركزية",
    area: 135,
    price: 3800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-12",
    duration: 730,
    isRadical: false,
  },

  // DAMMAM & KHOBAR (Eastern Province)
  {
    id: "prop-039",
    purpose: "rent",
    city: "الخبر",
    district: "القرطبة",
    address: "شارع الأمير سلطان",
    location: { type: "Point", coordinates: [50.182, 26.291] },
    title: "شقة بتصميم إسكندنافي",
    description: "ألوان فاتحة وتصميم هادئ جداً بالقرب من الراشد مول",
    area: 150,
    price: 7200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-13",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-040",
    purpose: "rent",
    city: "الخبر",
    district: "العليا",
    address: "شارع بشار بن برد",
    location: { type: "Point", coordinates: [50.191, 26.311] },
    title: "استديو فاخر للمهنيين",
    description: "قريب من أرامكو والظهران تكنو فالي، مؤثث بالكامل",
    area: 65,
    price: 4900,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-04-14",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-041",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفرسان",
    address: "طريق الملك فهد",
    location: { type: "Point", coordinates: [50.012, 26.352] },
    title: "فيلا مودرن زاوية",
    description: "مساحة واسعة للحديقة مع غرفة خادمة وغرفة غسيل",
    area: 350,
    price: 12500,
    bedrooms: 5,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-04-15",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-042",
    purpose: "rent",
    city: "الخبر",
    district: "العزيزية",
    address: "شارع الستين",
    location: { type: "Point", coordinates: [50.155, 26.155] },
    title: "شالية خاص على البحر",
    description: "يصلح للسكن الدائم أو كاستراحة خاصة نهاية الأسبوع",
    area: 200,
    price: 8000,
    bedrooms: 2,
    bathrooms: 3,
    propertyType: "villa",
    listedAt: "2025-04-16",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-043",
    purpose: "rent",
    city: "الدمام",
    district: "حي طيبة",
    address: "شارع عبدالرحمن بن عوف",
    location: { type: "Point", coordinates: [50.045, 26.388] },
    title: "شقة واسعة تشطيب سوبر لوكس",
    description: "ديكورات جبسية وإضاءات مخفية حديثة",
    area: 175,
    price: 4000,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-17",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-044",
    purpose: "rent",
    city: "الرياض",
    district: "حي نمار",
    address: "مخرج 28",
    location: { type: "Point", coordinates: [46.582, 24.585] },
    title: "دور أرضي واسع",
    description: "مدخل سيارة مستقل ومجلس خارجي (مشب)",
    area: 320,
    price: 5500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-18",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-045",
    purpose: "rent",
    city: "جدة",
    district: "البغدادية",
    address: "طريق المدينة",
    location: { type: "Point", coordinates: [39.185, 21.492] },
    title: "مكتب/سكن إداري",
    description: "موقع استراتيجي في وسط المدينة يصلح للسكن أو العمل",
    area: 110,
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-19",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-046",
    purpose: "rent",
    city: "الرياض",
    district: "النخيل",
    address: "شارع سالم بن معقل",
    location: { type: "Point", coordinates: [46.625, 24.745] },
    title: "شقة ذكية (Smart Home)",
    description: "تحكم كامل بالإضاءة والتكييف عبر الجوال",
    area: 155,
    price: 13000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-20",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-047",
    purpose: "rent",
    city: "الخبر",
    district: "البحر",
    address: "كورنيش الخبر",
    location: { type: "Point", coordinates: [50.222, 26.285] },
    title: "بنتهاوس ملكي",
    description: "أعلى برج في الخبر بإطلالة 360 درجة",
    area: 450,
    price: 35000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "apartment",
    listedAt: "2025-04-21",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-048",
    purpose: "rent",
    city: "الدمام",
    district: "الزهور",
    address: "شارع المستشفى",
    location: { type: "Point", coordinates: [50.105, 26.441] },
    title: "شقة عائلية بسيطة",
    description: "قريبة من جميع الخدمات الطبية والأسواق العامة",
    area: 140,
    price: 3000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-22",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-049",
    purpose: "rent",
    city: "جدة",
    district: "أبحر الجنوبية",
    address: "شارع الكورنيش",
    location: { type: "Point", coordinates: [39.112, 21.725] },
    title: "شقة سياحية فاخرة",
    description: "قريبة من مرسى اليخوت والمطاعم الفاخرة",
    area: 165,
    price: 10500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-23",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-050",
    purpose: "rent",
    city: "الرياض",
    district: "الملز",
    address: "شارع جرير",
    location: { type: "Point", coordinates: [46.725, 24.675] },
    title: "شقة كلاسيكية واسعة",
    description: "في قلب الرياض، تتميز بمساحات غرف كبيرة جداً",
    area: 195,
    price: 4500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-24",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-051",
    purpose: "sale",
    city: "جدة",
    district: "الشاطئ",
    address: "طريق الملك عبدالعزيز",
    location: { type: "Point", coordinates: [39.112, 21.616] },
    title: "فيلا مودرن إطلالة بحرية",
    description: "فيلا فاخرة بتصميم حديث تطل مباشرة على واجهة جدة البحرية",
    area: 450,
    price: 5200000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2023-11-12",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-052",
    purpose: "rent",
    city: "الدمام",
    district: "الفيصلية",
    address: "شارع عمر بن الخطاب",
    location: { type: "Point", coordinates: [50.071, 26.392] },
    title: "شقة عائلية هادئة",
    description: "قريبة من جميع الخدمات والمجمعات التجارية في الدمام",
    area: 160,
    price: 3200,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2024-01-15",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-053",
    purpose: "rent",
    city: "الرياض",
    district: "النرجس",
    address: "طريق أبي بكر الصديق",
    location: { type: "Point", coordinates: [46.642, 24.843] },
    title: "مكتب إداري فاخر",
    description: "مساحة مكتبية جاهزة في منطقة شمال الرياض الحيوية",
    area: 120,
    price: 8500,
    bedrooms: 0,
    bathrooms: 2,
    propertyType: "office",
    listedAt: "2025-02-01",
    duration: 8760,
    isRadical: false,
  },
  {
    id: "prop-054",
    purpose: "sale",
    city: "أبها",
    district: "المحالة",
    address: "شارع الاربعين",
    location: { type: "Point", coordinates: [42.615, 18.252] },
    title: "فيلا ريفية في أجواء جبلية",
    description: "تتميز بإطلالة رائعة على الجبال ومساحات خضراء واسعة",
    area: 600,
    price: 1850000,
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2022-06-20",
    duration: 4380,
    isRadical: false,
  },
  {
    id: "prop-055",
    purpose: "rent",
    city: "الخبر",
    district: "الحزام الذهبي",
    address: "شارع الأمير حمود",
    location: { type: "Point", coordinates: [50.203, 26.295] },
    title: "شقة لوكس بالخبر",
    description: "تشطيبات فاخرة ونظام دخول ذكي في أرقى أحياء الخبر",
    area: 140,
    price: 5500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-05-10",
    duration: 720,
    isRadical: true,
  },
  {
    id: "prop-056",
    purpose: "sale",
    city: "مكة المكرمة",
    district: "بطحاء قريش",
    address: "شارع الهلال",
    location: { type: "Point", coordinates: [39.845, 21.365] },
    title: "شقة تمليك قريبة من الحرم",
    description: "استثمار عقاري ممتاز في مكة المكرمة، تبعد 15 دقيقة عن الحرم",
    area: 180,
    price: 750000,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2021-09-05",
    duration: 2160,
    isRadical: false,
  },
  {
    id: "prop-057",
    purpose: "rent",
    city: "المدينة المنورة",
    district: "بني حارثة",
    address: "طريق المطار",
    location: { type: "Point", coordinates: [39.635, 24.512] },
    title: "مكتب تجاري واسع",
    description: "موقع استراتيجي على طريق المطار الرئيسي",
    area: 210,
    price: 12000,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "office",
    listedAt: "2024-08-22",
    duration: 24,
    isRadical: false,
  },
  {
    id: "prop-058",
    purpose: "sale",
    city: "تبوك",
    district: "المروج",
    address: "طريق الملك فيصل",
    location: { type: "Point", coordinates: [36.555, 28.383] },
    title: "فيلا واسعة بتبوك",
    description: "بناء شخصي بجودة عالية وموقع مميز في شمال تبوك",
    area: 500,
    price: 1350000,
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2020-03-14",
    duration: 1440,
    isRadical: false,
  },
  {
    id: "prop-059",
    purpose: "rent",
    city: "الرياض",
    district: "العليا",
    address: "خلف برج المملكة",
    location: { type: "Point", coordinates: [46.669, 24.711] },
    title: "شقة عزاب فندقية",
    description: "مؤثثة بالكامل بتصميم عصري في قلب منطقة الأعمال",
    area: 85,
    price: 6000,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-10-30",
    duration: 168,
    isRadical: true,
  },
  {
    id: "prop-060",
    purpose: "sale",
    city: "بريدة",
    district: "حي الريان",
    address: "طريق عمر بن الخطاب",
    location: { type: "Point", coordinates: [43.942, 26.355] },
    title: "فيلا دورين ببريدة",
    description: "تصميم كلاسيكي واسع مع ملحق خارجي ومواقف سيارات",
    area: 400,
    price: 1100000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2022-12-01",
    duration: 5000,
    isRadical: false,
  },
  {
    id: "prop-061",
    purpose: "rent",
    city: "الخبر",
    district: "قرطبة",
    address: "شارع خالد بن الوليد",
    location: { type: "Point", coordinates: [50.181, 26.312] },
    title: "شقة استوديو راقية",
    description: "مناسبة جداً للمهنيين والموظفين في أرامكو",
    area: 55,
    price: 2800,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2023-04-18",
    duration: 72,
    isRadical: false,
  },
  {
    id: "prop-062",
    purpose: "sale",
    city: "جدة",
    district: "الروضة",
    address: "شارع حمد الجاسر",
    location: { type: "Point", coordinates: [39.145, 21.562] },
    title: "مكتب استثماري في الروضة",
    description: "مكتب بموقع حيوي جداً في مركز تجاري مرموق",
    area: 110,
    price: 1250000,
    bedrooms: 0,
    bathrooms: 2,
    propertyType: "office",
    listedAt: "2024-11-15",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-063",
    purpose: "rent",
    city: "حائل",
    district: "النقرة",
    address: "شارع الثلاثين",
    location: { type: "Point", coordinates: [41.675, 27.491] },
    title: "شقة دور أرضي واسعة",
    description: "مدخل خاص وحوش جانبي في حي هادئ",
    area: 210,
    price: 2200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-01-20",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-064",
    purpose: "sale",
    city: "الرياض",
    district: "الملز",
    address: "شارع الفرزدق",
    location: { type: "Point", coordinates: [46.732, 24.665] },
    title: "عمارة سكنية قديمة",
    description: "فرصة استثمارية للتطوير أو الترميم في وسط الرياض",
    area: 350,
    price: 2800000,
    bedrooms: 8,
    bathrooms: 8,
    propertyType: "apartment",
    listedAt: "2020-07-11",
    duration: 8760,
    isRadical: true,
  },
  {
    id: "prop-065",
    purpose: "rent",
    city: "الجبيل",
    district: "جلمودة",
    address: "شارع اللؤلؤ",
    location: { type: "Point", coordinates: [49.521, 27.112] },
    title: "فيلا مودرن للإيجار",
    description: "فيلا راقية جداً بتجهيزات حديثة تناسب العائلات الكبيرة",
    area: 380,
    price: 9000,
    bedrooms: 4,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2024-05-30",
    duration: 2190,
    isRadical: false,
  },
  {
    id: "prop-066",
    purpose: "sale",
    city: "نجران",
    district: "حي الفهد",
    address: "شارع الملك عبدالعزيز",
    location: { type: "Point", coordinates: [44.135, 17.512] },
    title: "فيلا واسعة للبيع",
    description: "فيلا فخمة مع مجالس خارجية ومواقف مغطاة",
    area: 750,
    price: 1600000,
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2021-02-25",
    duration: 4380,
    isRadical: false,
  },
  {
    id: "prop-067",
    purpose: "rent",
    city: "الطائف",
    district: "شهار",
    address: "شارع الستين",
    location: { type: "Point", coordinates: [40.405, 21.251] },
    title: "شقة سياحية موسمية",
    description: "إطلالة خلابة وتجهيزات كاملة للمصطافين",
    area: 120,
    price: 4000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-06-15",
    duration: 720,
    isRadical: false,
  },
  {
    id: "prop-068",
    purpose: "sale",
    city: "الخبر",
    district: "حي الشاطئ",
    address: "شارع تركي بن عبدالعزيز",
    location: { type: "Point", coordinates: [50.221, 26.335] },
    title: "مبنى تجاري - مكاتب",
    description: "مبنى مكاتب مستقل بواجهة زجاجية حديثة",
    area: 900,
    price: 12000000,
    bedrooms: 0,
    bathrooms: 10,
    propertyType: "office",
    listedAt: "2023-08-01",
    duration: 8760,
    isRadical: true,
  },
  {
    id: "prop-069",
    purpose: "rent",
    city: "خميس مشيط",
    district: "الرصراص",
    address: "شارع القاعدة الجوية",
    location: { type: "Point", coordinates: [42.742, 18.291] },
    title: "شقة واسعة ونظيفة",
    description: "قريبة من القاعدة الجوية والخدمات الأساسية",
    area: 175,
    price: 2500,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2024-12-10",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-070",
    purpose: "sale",
    city: "الدمام",
    district: "حي الشاطئ",
    address: "شارع الخليج",
    location: { type: "Point", coordinates: [50.115, 26.465] },
    title: "دوبلكس عصري فاخر",
    description: "تصميم  كلاسيك و تكييف مركزي",
    area: 320,
    price: 2450000,
    bedrooms: 4,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-03-20",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-071",
    purpose: "sale",
    city: "ينبع",
    district: "الشرم",
    address: "شارع الواجهة البحرية",
    location: { type: "Point", coordinates: [38.063, 24.112] },
    title: "شاليه مودرن بمسبح خاص",
    description: "إطلالة مباشرة على البحر الأحمر وتصميم عصري مثالي للاستجمام",
    area: 320,
    price: 2100000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2024-07-15",
    duration: 2190,
    isRadical: false,
  },
  {
    id: "prop-072",
    purpose: "rent",
    city: "الهفوف",
    district: "المزروع",
    address: "بالقرب من جامعة الملك فيصل",
    location: { type: "Point", coordinates: [49.588, 25.352] },
    title: "شقة طلابية مجهزة",
    description: "شقة قريبة جداً من الجامعة، مناسبة للطلاب والمهنيين الجدد",
    area: 95,
    price: 1800,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-01-10",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-073",
    purpose: "sale",
    city: "الجبيل",
    district: "جلمودة",
    address: "شارع التحلية",
    location: { type: "Point", coordinates: [49.525, 27.118] },
    title: "فيلا سكنية فاخرة",
    description: "بناء الهيئة الملكية، جودة عالية جداً وتوزيع غرف ذكي",
    area: 400,
    price: 1950000,
    bedrooms: 5,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2022-03-22",
    duration: 4380,
    isRadical: true,
  },
  {
    id: "prop-074",
    purpose: "rent",
    city: "الخرج",
    district: "الهدا",
    address: "طريق الملك فهد",
    location: { type: "Point", coordinates: [47.311, 24.152] },
    title: "محل تجاري واسع",
    description: "موقع حيوي على طريق الملك فهد الرئيسي، يصلح لجميع الأنشطة",
    area: 85,
    price: 4500,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "office",
    listedAt: "2024-11-05",
    duration: 24,
    isRadical: false,
  },
  {
    id: "prop-075",
    purpose: "sale",
    city: "سكاكا",
    district: "الربوة",
    address: "حي الربوة العام",
    location: { type: "Point", coordinates: [40.211, 29.972] },
    title: "منزل شعبي مرمم",
    description: "منزل بتصميم تراثي تم ترميمه بالكامل، يقع في منطقة هادئة",
    area: 250,
    price: 650000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2021-08-14",
    duration: 1440,
    isRadical: false,
  },
  {
    id: "prop-076",
    purpose: "rent",
    city: "عرعر",
    district: "المساعدية",
    address: "شارع ولي العهد",
    location: { type: "Point", coordinates: [41.025, 30.982] },
    title: "شقة عوائل كبيرة",
    description: "غرف واسعة ومطبخ راكب، قريبة من الخدمات الصحية",
    area: 180,
    price: 2200,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-05-20",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-077",
    purpose: "sale",
    city: "جيزان",
    district: "مخطط الورود",
    address: "طريق الكورنيش الشمالي",
    location: { type: "Point", coordinates: [42.565, 16.902] },
    title: "فيلا تمليك دورين",
    description: "تصميم حديث بالقرب من شاطئ جيزان، تشطيبات سوبر لوكس",
    area: 350,
    price: 1450000,
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2023-06-30",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-078",
    purpose: "rent",
    city: "نجران",
    district: "الفيصلية",
    address: "شارع الملك سعود",
    location: { type: "Point", coordinates: [44.142, 17.512] },
    title: "شقة مفروشة راقية",
    description: "أثاث جديد وتجهيزات متكاملة، تكييف مركزي",
    area: 130,
    price: 3500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-02-12",
    duration: 168,
    isRadical: false,
  },
  {
    id: "prop-079",
    purpose: "sale",
    city: "الباحة",
    district: "رغدان",
    address: "بالقرب من غابة رغدان",
    location: { type: "Point", coordinates: [41.472, 20.021] },
    title: "فيلا جبلية بإطلالة",
    description: "فيلا بتصميم رائع مطلة على منحدرات الباحة الخضراء",
    area: 500,
    price: 1800000,
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2020-05-05",
    duration: 8760,
    isRadical: false,
  },
  {
    id: "prop-080",
    purpose: "rent",
    city: "بريدة",
    district: "الأفق",
    address: "طريق الملك عبدالله",
    location: { type: "Point", coordinates: [43.975, 26.342] },
    title: "مكتب إداري مجهز",
    description: "مساحة مكتبية مفتوحة جاهزة للتشغيل الفوري",
    area: 150,
    price: 7000,
    bedrooms: 0,
    bathrooms: 2,
    propertyType: "office",
    listedAt: "2024-09-01",
    duration: 72,
    isRadical: true,
  },
  {
    id: "prop-081",
    purpose: "sale",
    city: "عنيزة",
    district: "حي الفاخرية",
    address: "شارع الشبيلي",
    location: { type: "Point", coordinates: [43.992, 26.102] },
    title: "استراحة سكنية",
    description: "استراحة مجهزة بملحق ومسطحات خضراء ومسبح",
    area: 600,
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "villa",
    listedAt: "2021-12-10",
    duration: 4380,
    isRadical: false,
  },
  {
    id: "prop-082",
    purpose: "rent",
    city: "القطيف",
    district: "المجيدية",
    address: "شارع القدس",
    location: { type: "Point", coordinates: [49.998, 26.542] },
    title: "شقة عائلية وسط المدينة",
    description: "موقع استراتيجي بالقرب من الأسواق التجارية الرئيسية",
    area: 145,
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-18",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-083",
    purpose: "sale",
    city: "حفر الباطن",
    district: "الربوة",
    address: "طريق الكويت",
    location: { type: "Point", coordinates: [45.955, 28.422] },
    title: "فيلا فخمة واسعة",
    description: "تصميم فخم مع مجلس خارجي وحوش يسع 3 سيارات",
    area: 550,
    price: 1200000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2022-02-15",
    duration: 2190,
    isRadical: false,
  },
  {
    id: "prop-084",
    purpose: "rent",
    city: "الظهران",
    district: "الدوحة الجنوبية",
    address: "شارع عبدالله بن عباس",
    location: { type: "Point", coordinates: [50.165, 26.312] },
    title: "شقة استوديو راقية",
    description: "قريبة جداً من أرامكو وجامعة البترول، مناسبة للمهندسين",
    area: 65,
    price: 3200,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-03-25",
    duration: 72,
    isRadical: true,
  },
  {
    id: "prop-085",
    purpose: "sale",
    city: "القريات",
    district: "الفيصلية",
    address: "بالقرب من الجمرك",
    location: { type: "Point", coordinates: [37.342, 31.322] },
    title: "منزل سكني كبير",
    description: "موقع ممتاز للمسافرين والموظفين في منفذ الحديثة",
    area: 400,
    price: 900000,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2020-11-30",
    duration: 1440,
    isRadical: false,
  },
  {
    id: "prop-086",
    purpose: "rent",
    city: "الرس",
    district: "حي الروضة",
    address: "شارع الجمل",
    location: { type: "Point", coordinates: [43.502, 25.862] },
    title: "شقة دور أول مستقلة",
    description: "مدخل خاص ومواقف مظللة في حي هادئ",
    area: 160,
    price: 1900,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2024-06-12",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-087",
    purpose: "sale",
    city: "بيشة",
    district: "الخالدية",
    address: "طريق الملك عبدالعزيز",
    location: { type: "Point", coordinates: [42.612, 20.012] },
    title: "فيلا دور واحد",
    description: "بناء حديث وتصميم شعبي بلمسة عصرية",
    area: 300,
    price: 780000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "villa",
    listedAt: "2023-01-20",
    duration: 2190,
    isRadical: false,
  },
  {
    id: "prop-088",
    purpose: "rent",
    city: "النماص",
    district: "الظهارة",
    address: "طريق أبها الطائف",
    location: { type: "Point", coordinates: [42.152, 19.112] },
    title: "شقة بإطلالة ضبابية",
    description: "في أعالي جبال السروات، مناسبة للصيف والأجواء الباردة",
    area: 110,
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-07-01",
    duration: 720,
    isRadical: false,
  },
  {
    id: "prop-089",
    purpose: "sale",
    city: "جدة",
    district: "المحمدية",
    address: "شارع الأمير سلطان",
    location: { type: "Point", coordinates: [39.122, 21.642] },
    title: "مكتب تجاري براند",
    description: "مكتب فخم في برج إداري حديث بشارع الأمير سلطان",
    area: 200,
    price: 3500000,
    bedrooms: 0,
    bathrooms: 3,
    propertyType: "office",
    listedAt: "2024-12-05",
    duration: 8760,
    isRadical: true,
  },
  {
    id: "prop-090",
    purpose: "rent",
    city: "الرياض",
    district: "حي السفارات",
    address: "ساحة الكندي",
    location: { type: "Point", coordinates: [46.622, 24.682] },
    title: "شقة دبلوماسية فاخرة",
    description: "نظام أمني عالي، تشطيبات عالمية، في أرقى مناطق الرياض",
    area: 210,
    price: 15000,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-08-15",
    duration: 730,
    isRadical: true,
  },
  {
    id: "prop-091",
    purpose: "sale",
    city: "مكة المكرمة",
    district: "العزيزية",
    address: "خلف مركز فقيه التجاري",
    location: { type: "Point", coordinates: [39.865, 21.392] },
    title: "شقة فندقية استثمارية",
    description: "فرصة استثمارية ذهبية في العزيزية، مؤجرة حالياً",
    area: 140,
    price: 1150000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2021-04-10",
    duration: 4380,
    isRadical: false,
  },
  {
    id: "prop-092",
    purpose: "rent",
    city: "تاروت",
    district: "الشاطئ",
    address: "شارع كورنيش تاروت",
    location: { type: "Point", coordinates: [50.052, 26.562] },
    title: "شقة بحرية هادئة",
    description: "إطلالة مباشرة على بحر تاروت وهدوء تام بعيداً عن الصخب",
    area: 155,
    price: 2600,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2024-10-22",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-093",
    purpose: "sale",
    city: "أبها",
    district: "حي المنهل",
    address: "طريق الحزام",
    location: { type: "Point", coordinates: [42.508, 18.222] },
    title: "فيلا مودرن بتصميم مميز",
    description: "تجمع بين الحجر الطبيعي والزجاج، في موقع مرتفع ومميز",
    area: 420,
    price: 2600000,
    bedrooms: 5,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-01-05",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-094",
    purpose: "rent",
    city: "المدينة المنورة",
    district: "العوالي",
    address: "طريق الهجرة",
    location: { type: "Point", coordinates: [39.632, 24.442] },
    title: "مكتب تجاري دور كامل",
    description: "مساحة واسعة جداً تصلح لمقر شركة أو مركز تدريب",
    area: 300,
    price: 18000,
    bedrooms: 0,
    bathrooms: 4,
    propertyType: "office",
    listedAt: "2023-09-18",
    duration: 24,
    isRadical: false,
  },
  {
    id: "prop-095",
    purpose: "sale",
    city: "المجمعة",
    district: "حي المستشفى",
    address: "طريق الملك سلمان",
    location: { type: "Point", coordinates: [45.342, 25.912] },
    title: "فيلا سكنية واسعة",
    description: "قريبة من جميع الخدمات والدوائر الحكومية في المجمعة",
    area: 450,
    price: 950000,
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2022-07-25",
    duration: 4380,
    isRadical: false,
  },
  {
    id: "prop-096",
    purpose: "rent",
    city: "الدواسر",
    district: "حي الخماسين",
    address: "شارع المستشفى",
    location: { type: "Point", coordinates: [44.782, 20.452] },
    title: "شقة عوائل جديدة",
    description: "تشطيب حديث وأول ساكن، موقع حيوي وسهل الوصول",
    area: 170,
    price: 2000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-06-10",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-097",
    purpose: "sale",
    city: "تبوك",
    district: "حي المصيف",
    address: "شارع الخمسين",
    location: { type: "Point", coordinates: [36.562, 28.402] },
    title: "فيلا بتصميم نيو كلاسيك",
    description: "فيلا فاخرة بمساحة كبيرة وتوزيع ممتاز للغرف والصالات",
    area: 520,
    price: 1750000,
    bedrooms: 6,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2024-02-14",
    duration: 2190,
    isRadical: false,
  },
  {
    id: "prop-098",
    purpose: "rent",
    city: "صبيا",
    district: "حي المطار",
    address: "طريق جيزان",
    location: { type: "Point", coordinates: [42.632, 17.152] },
    title: "شقة سكنية واسعة",
    description: "تكييف اسبليت راكب ومطبخ مجهز، في قلب صبيا",
    area: 140,
    price: 1600,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-09-01",
    duration: 730,
    isRadical: false,
  },
  {
    id: "prop-099",
    purpose: "sale",
    city: "الدمام",
    district: "حي ضاحية الملك فهد",
    address: "الشارع التجاري",
    location: { type: "Point", coordinates: [50.022, 26.412] },
    title: "فيلا دبلكس منفصلة",
    description: "تصميم حديث بواجهة شرقية وبناء عالي الجودة",
    area: 300,
    price: 1350000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2023-11-20",
    duration: 2190,
    isRadical: true,
  },
  {
    id: "prop-100",
    purpose: "rent",
    city: "ينبع الصناعية",
    district: "السميري",
    address: "شارع النواة",
    location: { type: "Point", coordinates: [38.102, 23.952] },
    title: "شقة سكنية راقية",
    description: "في قلب منطقة ينبع الصناعية، قريبة من مراكز التسوق",
    area: 125,
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-11-01",
    duration: 730,
    isRadical: false,
  }
];

export default properties;
