import { Property } from "@/app/types/property-type";

const properties: Property[] = [
  {
    id: "prop-001",
    purpose: "rent",
    city: "الرياض",
    district: "الملز",
    address: "شارع الأحساء",
    location: {
      type: "Point",
      coordinates: [46.7201, 24.6663],
    },
    title: "شقة مفروشة للإيجار",
    description: "شقة حديثة قريبة من الخدمات",
    area: 120,
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-01-20",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-002",
    purpose: "sale",
    city: "الرياض",
    district: "الياسمين",
    address: "طريق أنس بن مالك",
    location: {
      type: "Point",
      coordinates: [46.6435, 24.8332],
    },
    title: "فيلا للبيع",
    description: "فيلا فاخرة بتصميم عصري",
    area: 420,
    price: 2500000,
    duration: 730,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2025-02-05",
    isLuxury: true,
  },
  {
    id: "prop-003",
    purpose: "rent",
    city: "الرياض",
    district: "العليا",
    address: "شارع العليا العام",
    location: {
      type: "Point",
      coordinates: [46.6753, 24.6902],
    },
    title: "مكتب للإيجار",
    description: "مكتب مناسب للشركات الناشئة",
    area: 85,
    price: 1800,
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "office",
    listedAt: "2025-02-18",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-004",
    purpose: "rent",
    city: "الرياض",
    district: "النرجس",
    address: "شارع عثمان بن عفان",
    location: {
      type: "Point",
      coordinates: [46.6679, 24.8576],
    },
    title: "شقة فاخرة للإيجار",
    description: "تشطيب راقي وموقع مميز",
    area: 160,
    price: 5200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-01",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-005",
    purpose: "sale",
    city: "الرياض",
    district: "الشفا",
    address: "شارع ديراب",
    location: {
      type: "Point",
      coordinates: [46.6402, 24.5743],
    },
    title: "دور أرضي للبيع",
    description: "مناسب للعائلات وموقع هادئ",
    area: 300,
    price: 1350000,
    bedrooms: 4,
    duration: 72,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-01-28",
    isLuxury: false,
  },
  {
    id: "prop-006",
    purpose: "rent",
    city: "الرياض",
    district: "اليرموك",
    address: "شارع النجاح",
    location: {
      type: "Point",
      coordinates: [46.7845, 24.7641],
    },
    title: "شقة عائلية للإيجار",
    description: "قريبة من المدارس والخدمات",
    area: 140,
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-02-12",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-007",
    purpose: "sale",
    city: "الرياض",
    district: "الملقا",
    address: "طريق الملك فهد",
    location: {
      type: "Point",
      coordinates: [46.6408, 24.8125],
    },
    title: "شقة تمليك حديثة",
    description: "بجوار المراكز التجارية",
    area: 180,
    price: 980000,
    bedrooms: 3,
    bathrooms: 3,
    duration: 24,
    propertyType: "apartment",
    listedAt: "2025-02-22",
    isLuxury: true,
  },
  {
    id: "prop-008",
    purpose: "rent",
    city: "الرياض",
    district: "قرطبة",
    address: "شارع سعيد بن زيد",
    location: {
      type: "Point",
      coordinates: [46.7412, 24.8117],
    },
    title: "مكتب إداري للإيجار",
    description: "موقع استراتيجي للشركات",
    area: 110,
    price: 3500,
    bedrooms: 0,
    bathrooms: 2,
    propertyType: "office",
    listedAt: "2025-03-05",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-009",
    purpose: "sale",
    city: "الرياض",
    district: "النسيم",
    address: "شارع الأربعين",
    location: {
      type: "Point",
      coordinates: [46.7934, 24.7041],
    },
    title: "فيلا دوبلكس للبيع",
    description: "تشطيب ممتاز وسعر مناسب",
    area: 360,
    price: 1650000,
    bedrooms: 4,
    bathrooms: 5,
    duration: 72,
    propertyType: "villa",
    listedAt: "2025-01-15",
    isLuxury: false,
  },
  {
    id: "prop-010",
    purpose: "rent",
    city: "الرياض",
    district: "حطين",
    address: "شارع الأمير محمد بن سعد",
    location: {
      type: "Point",
      coordinates: [46.6239, 24.8221],
    },
    title: "شقة فاخرة مطلة",
    description: "إطلالة مميزة وتصميم عصري",
    area: 200,
    price: 7500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-10",
    duration: 730,
    isLuxury: true,
  },
  // RIYADH
  {
    id: "prop-011",
    purpose: "rent",
    city: "الرياض",
    district: "النرجس",
    address: "طريق الملك سلمان",
    location: { type: "Point", coordinates: [46.642, 24.845] },
    title: "مودرن فيلا صغيرة",
    description: "فيلا مودرن بتصميم ذكي ومساحات استغلالية رائعة",
    area: 250,
    price: 12000,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-03-12",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-012",
    purpose: "rent",
    city: "الرياض",
    district: "الملقا",
    address: "شارع أنس بن مالك",
    location: { type: "Point", coordinates: [46.615, 24.808] },
    title: "استديو مؤثث بالكامل",
    description: "استديو فاخر للعزاب في أرقى أحياء الشمال",
    area: 55,
    price: 4500,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-03-14",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-013",
    purpose: "rent",
    city: "الرياض",
    district: "الياسمين",
    address: "شارع القلعة",
    location: { type: "Point", coordinates: [46.645, 24.815] },
    title: "شقة واسعة للعائلات",
    description: "قريبة من جميع الخدمات والمدارس العالمية",
    area: 160,
    price: 6000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-15",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-014",
    purpose: "rent",
    city: "الرياض",
    district: "حي السفارات",
    address: "ساحة الكندي",
    location: { type: "Point", coordinates: [46.628, 24.678] },
    title: "دوبلكس في حي السفارات",
    description: "خصوصية تامة وأمان عالي في منطقة هادئة",
    area: 320,
    price: 25000,
    bedrooms: 4,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-03-16",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-015",
    purpose: "rent",
    city: "الرياض",
    district: "العقيق",
    address: "طريق الملك فهد",
    location: { type: "Point", coordinates: [46.634, 24.782] },
    title: "شقة مطلة على المركز المالي",
    description: "إطلالة بانورامية على KAFD وتصميم عصري",
    area: 140,
    price: 8500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-18",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-016",
    purpose: "rent",
    city: "الرياض",
    district: "الصحافة",
    address: "شارع العليا",
    location: { type: "Point", coordinates: [46.631, 24.801] },
    title: "بنتهاوس مع سطح خاص",
    description: "مساحة خارجية كبيرة للتنزه واللقاءات العائلية",
    area: 210,
    price: 9000,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-20",
    duration: 730,
    isLuxury: true,
  },

  // JEDDAH
  {
    id: "prop-017",
    purpose: "rent",
    city: "جدة",
    district: "الشاطئ",
    address: "طريق الكورنيش",
    location: { type: "Point", coordinates: [39.112, 21.604] },
    title: "شقة فاخرة واجهة بحرية",
    description: "استيقظ على صوت الأمواج وإطلالة البحر الأحمر",
    area: 280,
    price: 15000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-21",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-018",
    purpose: "rent",
    city: "جدة",
    district: "الروضة",
    address: "شارع حمد الجاسر",
    location: { type: "Point", coordinates: [39.148, 21.562] },
    title: "شقة في قلب الروضة",
    description: "شقة هادئة في أرقى شوارع جدة الحيوية",
    area: 180,
    price: 7000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-22",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-019",
    purpose: "rent",
    city: "جدة",
    district: "أبحر الشمالية",
    address: "شارع العابر",
    location: { type: "Point", coordinates: [39.105, 21.745] },
    title: "فيلا مودرن بمسبح خاص",
    description: "تصميم عصري واسع مع حديقة ومسبح",
    area: 400,
    price: 18000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "villa",
    listedAt: "2025-03-23",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-020",
    purpose: "rent",
    city: "جدة",
    district: "السلامة",
    address: "شارع صاري",
    location: { type: "Point", coordinates: [39.155, 21.585] },
    title: "شقة اقتصادية مريحة",
    description: "قريبة من المجمعات التجارية والمطاعم",
    area: 120,
    price: 4000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-24",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-021",
    purpose: "rent",
    city: "جدة",
    district: "الحمراء",
    address: "طريق الأندلس",
    location: { type: "Point", coordinates: [39.172, 21.515] },
    title: "شقة كلاسيكية واسعة",
    description: "أسقف عالية ومساحات واسعة بالقرب من نافورة جدة",
    area: 220,
    price: 8500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-25",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-022",
    purpose: "rent",
    city: "جدة",
    district: "المحمدية",
    address: "شارع الأمير سلطان",
    location: { type: "Point", coordinates: [39.128, 21.642] },
    title: "دوبلكس عصري فاخر",
    description: "نظام ذكي وتكييف مركزي وتشطيبات ملكية",
    area: 260,
    price: 13000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-03-26",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-023",
    purpose: "rent",
    city: "جدة",
    district: "البساتين",
    address: "طريق الملك",
    location: { type: "Point", coordinates: [39.115, 21.685] },
    title: "جناح فندقي خاص",
    description: "استديو فاخر بخدمات تنظيف وصيانة دورية",
    area: 70,
    price: 6500,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-03-27",
    duration: 730,
    isLuxury: true,
  },

  // DAMMAM
  {
    id: "prop-024",
    purpose: "rent",
    city: "الدمام",
    district: "الشاطئ الشرقي",
    address: "طريق الخليج",
    location: { type: "Point", coordinates: [50.125, 26.452] },
    title: "شقة مطلة على الخليج",
    description: "إطلالة مباشرة على كورنيش الدمام",
    area: 190,
    price: 6500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-28",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-025",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفيصلية",
    address: "شارع عمر بن الخطاب",
    location: { type: "Point", coordinates: [50.082, 26.395] },
    title: "فيلا عائلية كبيرة",
    description: "فيلا مستقلة مع كراج خاص لسيارتين",
    area: 450,
    price: 11000,
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-03-29",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-026",
    purpose: "rent",
    city: "الدمام",
    district: "حي المنار",
    address: "شارع الإمام علي بن أبي طالب",
    location: { type: "Point", coordinates: [50.055, 26.375] },
    title: "شقة أرضية بحوش",
    description: "مدخل خاص وحوش جانبي مناسب للأطفال",
    area: 170,
    price: 3500,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-03-30",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-027",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفاخرية",
    address: "شارع المتنبي",
    location: { type: "Point", coordinates: [50.035, 26.345] },
    title: "شقة مودرن جديدة",
    description: "عمارة جديدة كلياً بتصميم حديث وموقف خاص",
    area: 155,
    price: 4200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-03-31",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-028",
    purpose: "rent",
    city: "الدمام",
    district: "حي النزهة",
    address: "شارع عثمان بن عفان",
    location: { type: "Point", coordinates: [50.11, 26.415] },
    title: "شقة مؤثثة بالكامل",
    description: "أثاث ايكيا جديد ومطبخ متكامل الأجهزة",
    area: 130,
    price: 5500,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-01",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-029",
    purpose: "rent",
    city: "الدمام",
    district: "حي هجر",
    address: "طريق الرياض",
    location: { type: "Point", coordinates: [50.165, 26.285] },
    title: "فيلا للإيجار السنوي",
    description: "موقع استراتيجي بالقرب من جامعة الإمام عبدالرحمن",
    area: 300,
    price: 9500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-02",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-030",
    purpose: "rent",
    city: "الدمام",
    district: "حي الجوهرة",
    address: "شارع الخليج",
    location: { type: "Point", coordinates: [50.145, 26.442] },
    title: "شقة مطلة على الحديقة",
    description: "شقة هادئة جداً بإطلالة خضراء واسعة",
    area: 185,
    price: 5000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-03",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-031",
    purpose: "rent",
    city: "الرياض",
    district: "المصيف",
    address: "شارع زهير بن أبي سلمى",
    location: { type: "Point", coordinates: [46.6821, 24.7612] },
    title: "شقة مرممة بالكامل",
    description: "شقة في الدور الأول تم تجديدها بالكامل بمواد صحية فاخرة",
    area: 145,
    price: 4800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-05",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-032",
    purpose: "rent",
    city: "الرياض",
    district: "السليمانية",
    address: "شارع الثلاثين",
    location: { type: "Point", coordinates: [46.7011, 24.698] },
    title: "تاون هاوس في كمباوند هادئ",
    description: "بيئة سكنية آمنة مع مسبح مشترك وصالة ألعاب رياضية",
    area: 280,
    price: 16500,
    bedrooms: 3,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-06",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-033",
    purpose: "rent",
    city: "الرياض",
    district: "قرطبة",
    address: "طريق الثمامة",
    location: { type: "Point", coordinates: [46.732, 24.814] },
    title: "ملحق راقي بسطح خاص",
    description: "خصوصية تامة مع اطلالة ليلية جميلة على شمال الرياض",
    area: 110,
    price: 5200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-07",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-034",
    purpose: "rent",
    city: "الرياض",
    district: "الرائد",
    address: "طريق الملك عبدالله",
    location: { type: "Point", coordinates: [46.641, 24.721] },
    title: "شقة فاخرة بجوار الجامعة",
    description: "قريبة جداً من جامعة الملك سعود ومستشفى الملك خالد",
    area: 190,
    price: 9500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-08",
    duration: 730,
    isLuxury: true,
  },

  // JEDDAH
  {
    id: "prop-035",
    purpose: "rent",
    city: "جدة",
    district: "النعيم",
    address: "شارع حراء",
    location: { type: "Point", coordinates: [39.1412, 21.618] },
    title: "شقة واسعة جداً للعوائل",
    description: "مساحات مفتوحة وتوزيع ذكي للغرف في حي راقي ومكتمل الخدمات",
    area: 210,
    price: 6500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-04-09",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-036",
    purpose: "rent",
    city: "جدة",
    district: "المرجان",
    address: "طريق الملك عبدالعزيز",
    location: { type: "Point", coordinates: [39.101, 21.705] },
    title: "قصر مصغر بإطلالة بحرية",
    description: "تشطيبات ملكية، رخام إيطالي، ومصعد داخلي خاص",
    area: 600,
    price: 45000,
    bedrooms: 6,
    bathrooms: 7,
    propertyType: "villa",
    listedAt: "2025-04-10",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-037",
    purpose: "rent",
    city: "جدة",
    district: "النهضة",
    address: "شارع حراء",
    location: { type: "Point", coordinates: [39.125, 21.625] },
    title: "شقة دوبلكس مودرن",
    description: "تصميم طابقين مع سلم داخلي خشبي وتكييف مركزي",
    area: 240,
    price: 11000,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "apartment",
    listedAt: "2025-04-11",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-038",
    purpose: "rent",
    city: "جدة",
    district: "الصفا",
    address: "شارع السبعين",
    location: { type: "Point", coordinates: [39.201, 21.571] },
    title: "شقة اقتصادية نظيفة",
    description: "مثالية للعائلات الصغيرة قريبة من الأسواق المركزية",
    area: 135,
    price: 3800,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-12",
    duration: 730,
    isLuxury: false,
  },

  // DAMMAM & KHOBAR (Eastern Province)
  {
    id: "prop-039",
    purpose: "rent",
    city: "الخبر",
    district: "القرطبة",
    address: "شارع الأمير سلطان",
    location: { type: "Point", coordinates: [50.182, 26.291] },
    title: "شقة بتصميم إسكندنافي",
    description: "ألوان فاتحة وتصميم هادئ جداً بالقرب من الراشد مول",
    area: 150,
    price: 7200,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-13",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-040",
    purpose: "rent",
    city: "الخبر",
    district: "العليا",
    address: "شارع بشار بن برد",
    location: { type: "Point", coordinates: [50.191, 26.311] },
    title: "استديو فاخر للمهنيين",
    description: "قريب من أرامكو والظهران تكنو فالي، مؤثث بالكامل",
    area: 65,
    price: 4900,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "apartment",
    listedAt: "2025-04-14",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-041",
    purpose: "rent",
    city: "الدمام",
    district: "حي الفرسان",
    address: "طريق الملك فهد",
    location: { type: "Point", coordinates: [50.012, 26.352] },
    title: "فيلا مودرن زاوية",
    description: "مساحة واسعة للحديقة مع غرفة خادمة وغرفة غسيل",
    area: 350,
    price: 12500,
    bedrooms: 5,
    bathrooms: 5,
    propertyType: "villa",
    listedAt: "2025-04-15",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-042",
    purpose: "rent",
    city: "الخبر",
    district: "العزيزية",
    address: "شارع الستين",
    location: { type: "Point", coordinates: [50.155, 26.155] },
    title: "شالية خاص على البحر",
    description: "يصلح للسكن الدائم أو كاستراحة خاصة نهاية الأسبوع",
    area: 200,
    price: 8000,
    bedrooms: 2,
    bathrooms: 3,
    propertyType: "villa",
    listedAt: "2025-04-16",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-043",
    purpose: "rent",
    city: "الدمام",
    district: "حي طيبة",
    address: "شارع عبدالرحمن بن عوف",
    location: { type: "Point", coordinates: [50.045, 26.388] },
    title: "شقة واسعة تشطيب سوبر لوكس",
    description: "ديكورات جبسية وإضاءات مخفية حديثة",
    area: 175,
    price: 4000,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-17",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-044",
    purpose: "rent",
    city: "الرياض",
    district: "حي نمار",
    address: "مخرج 28",
    location: { type: "Point", coordinates: [46.582, 24.585] },
    title: "دور أرضي واسع",
    description: "مدخل سيارة مستقل ومجلس خارجي (مشب)",
    area: 320,
    price: 5500,
    bedrooms: 4,
    bathrooms: 4,
    propertyType: "villa",
    listedAt: "2025-04-18",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-045",
    purpose: "rent",
    city: "جدة",
    district: "البغدادية",
    address: "طريق المدينة",
    location: { type: "Point", coordinates: [39.185, 21.492] },
    title: "مكتب/سكن إداري",
    description: "موقع استراتيجي في وسط المدينة يصلح للسكن أو العمل",
    area: 110,
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-19",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-046",
    purpose: "rent",
    city: "الرياض",
    district: "النخيل",
    address: "شارع سالم بن معقل",
    location: { type: "Point", coordinates: [46.625, 24.745] },
    title: "شقة ذكية (Smart Home)",
    description: "تحكم كامل بالإضاءة والتكييف عبر الجوال",
    area: 155,
    price: 13000,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-20",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-047",
    purpose: "rent",
    city: "الخبر",
    district: "البحر",
    address: "كورنيش الخبر",
    location: { type: "Point", coordinates: [50.222, 26.285] },
    title: "بنتهاوس ملكي",
    description: "أعلى برج في الخبر بإطلالة 360 درجة",
    area: 450,
    price: 35000,
    bedrooms: 5,
    bathrooms: 6,
    propertyType: "apartment",
    listedAt: "2025-04-21",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-048",
    purpose: "rent",
    city: "الدمام",
    district: "الزهور",
    address: "شارع المستشفى",
    location: { type: "Point", coordinates: [50.105, 26.441] },
    title: "شقة عائلية بسيطة",
    description: "قريبة من جميع الخدمات الطبية والأسواق العامة",
    area: 140,
    price: 3000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "apartment",
    listedAt: "2025-04-22",
    duration: 730,
    isLuxury: false,
  },
  {
    id: "prop-049",
    purpose: "rent",
    city: "جدة",
    district: "أبحر الجنوبية",
    address: "شارع الكورنيش",
    location: { type: "Point", coordinates: [39.112, 21.725] },
    title: "شقة سياحية فاخرة",
    description: "قريبة من مرسى اليخوت والمطاعم الفاخرة",
    area: 165,
    price: 10500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-23",
    duration: 730,
    isLuxury: true,
  },
  {
    id: "prop-050",
    purpose: "rent",
    city: "الرياض",
    district: "الملز",
    address: "شارع جرير",
    location: { type: "Point", coordinates: [46.725, 24.675] },
    title: "شقة كلاسيكية واسعة",
    description: "في قلب الرياض، تتميز بمساحات غرف كبيرة جداً",
    area: 195,
    price: 4500,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "apartment",
    listedAt: "2025-04-24",
    duration: 730,
    isLuxury: false,
  },
];

export default properties;
